import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme'
import "./globals.css";

export const metadata: Metadata = {
  title: "CocoApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <AppRouterCacheProvider>
          <body>
            {children}
          </body>
        </AppRouterCacheProvider>
      </html>
    </ThemeProvider>
  );
}
